spring:
  data:
    mongodb:
      database: javapro
      host: localhost
      port: 27017
      username: root
      password: password
  redis:
    host: localhost
    port: 6379
admin:
  username: admin
  password: "{bcrypt}$2a$10$nLje5D9UzxJdd.OdpGgozOtvefbOt6o8n4YX.l.TerwMZ71HfHJpW"