spring:
  minio:
    url: http://localhost:9000
    bucket: media
    access-key: HTnfdNY10s1W6luh
    secret-key: brZUtLJYrxD4Xib46J0PHZ8k8iifvzv2
  data:
    mongodb:
      database: javapro
      host: localhost
      port: 27017
      username: root
      password: password
  redis:
    host: localhost
    port: 6379
admin:
  username: admin
  password: "{bcrypt}$2a$10$nLje5D9UzxJdd.OdpGgozOtvefbOt6o8n4YX.l.TerwMZ71HfHJpW"