spring:
  data:
    mongodb:
      database: javapro
      host: localhost
      port: 27017
      username: root
      password: password
  redis:
    host: localhost
    port: 6379
  security:
    user:
      name: admin
      password: admin