version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - ./mongo-volume:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:5.0.7
    volumes:
      - ./redis-data:/data
    stdin_open: true
    tty: true
    ports:
      - '6379:6379'